<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Moq" />
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\backend\FamilyTree.Domain\FamilyTree.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\backend\FamilyTree.Application\FamilyTree.Application.csproj" />
    <ProjectReference Include="..\..\..\src\backend\FamilyTree.Infrastructure\FamilyTree.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\backend\FamilyTree.Api\FamilyTree.Api.csproj" />
  </ItemGroup>

</Project>
